<?php

namespace Degustation\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
	{
		$queryBuilder = $this->createQueryBuilder('a');
	    $query = $queryBuilder->getQuery();
	    $results = $query->getResult();

	    return $results;
	}
}
